config/routes.rb
Events::Application.routes.draw do

  resources :events

  resources :organizations do 
    resources :events
  end

  root to: 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event_end_date, :event_end_time, :event_start_date, :event_start_time, :location, :name
  belongs_to :organization

  scope :today, lambda { where(event_start_date: Time.zone.now.all_day).order('events.event_start_time ASC') }
  scope :tomorrow, lambda { where(event_start_date: 1.day.from_now.all_day).order('events.event_start_date, events.event_start_time ASC') }
  
  def self.this_week
    two_days = Time.now.beginning_of_day + 2.days
    one_week = Time.now.end_of_day + 7.days
    where('events.event_start_date >= ? AND events.event_start_date <= ?', two_days, one_week).order('events.event_start_date, events.event_start_time ASC')
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :description, :name, :website
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events_today = Event.today
    @events_tomorrow = Event.tomorrow
    @events_this_week = Event.this_week

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @organization = Organization.find(params[:organization_id])
    @event = @organization.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @organization = Organization.find(params[:organization_id])
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @organization = Organization.find(params[:organization_id])
  end

  # POST /events
  # POST /events.json
  def create
    @organization = Organization.find(params[:organization_id])
    @event = @organization.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to organization_event_path(@organization, @event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    @organization = @event.organization

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to organization_event_path(@event.organization, @event), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/events/_form.html.erb
<%= form_for [@organization, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :event_start_date %><br />
      <%= f.text_field :event_start_date, class: "datepicker" %>
    </div>
    <div class="field">
      <%= f.label :event_start_time %><br />
      <%= f.text_field :event_start_time, class: "timepicker", placeholder: "e.g. 4pm or 8pm" %>
    </div>
    <div class="field">
      <%= f.label :event_end_date %><br />
      <%= f.text_field :event_end_date, class: "datepicker" %>
    </div>
    <div class="field">
      <%= f.label :event_end_time %><br />
      <%= f.text_field :event_end_time, class: "timepicker" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/edit.html.erb
<div class="updateform">
	<h1>Edit Event</h1>
	<%= render 'form' %>
</div>

app/views/events/index.html.erb
<div id="today" data-spy="affix" data-offset-top="200" class="stickyicky" >
    <a href="#now"><h2>Today</h2></a>
    <span>-</span>
    <a href="#tomorrow"><h2>Tomorrow</h2></a>
    <span>-</span>
    <a href="#later"><h2>This Week</h2></a>
</div>
<% @events_today.each do |event| %>
    <div class="row event-row text-center" id="now">
        <%= image_tag 'bruno.jpg' %>
        <div class="one_fourth">
            <h3>Who</h3>
            <%= link_to event.organization.name, event.organization %>
        </div>
        <div class="one_fourth">
            <h3>What</h3>
            <p>
                <%= link_to event.name, organization_event_path(event.organization, event) %><br>
            </p>
        </div>
        <div class="one_fourth">
            <h3>Where</h3>
            <p><%= event.location %></p>
        </div>
        <div class="one_fourth">
            <h3>When</h3>
            <p><%= event.event_start_date.strftime('%A') %> at <%= event.event_start_time.strftime('%l%P') %></p>
        </div>
    </div>
<% end %>

<% @events_tomorrow.each do |event| %>
    <div class="row event-row text-center" id="tomorrow">
        <%= image_tag 'tech.jpg' %>
        <div class="one_fourth">
            <h3>Who</h3>
            <%= link_to event.organization.name, event.organization %>
        </div>
        <div class="one_fourth">
            <h3>What</h3>
            <p>
                <%= link_to event.name, organization_event_path(event.organization, event) %><br>
            </p>
        </div>
        <div class="one_fourth">
            <h3>Where</h3>
            <p><%= event.location %></p>
        </div>
        <div class="one_fourth">
            <h3>When</h3>
            <p><%= event.event_start_date.strftime('%A') %> at <%= event.event_start_time.strftime('%l%P') %></p>
        </div>
    </div>
<% end %>

<% @events_this_week.each do |event| %>
    <div class="row event-row text-center" id="later">
        <%= image_tag 'best.jpg' %>
        <div class="one_fourth">
            <h3>Who</h3>
            <%= link_to event.organization.name, event.organization %>
        </div>
        <div class="one_fourth">
            <h3>What</h3>
            <p>
                <%= link_to event.name, organization_event_path(event.organization, event) %><br>
            </p>
        </div>
        <div class="one_fourth">
            <h3>Where</h3>
            <p><%= event.location %></p>
        </div>
        <div class="one_fourth">
            <h3>When</h3>
            <p><%= event.event_start_date.strftime('%A') %> at <%= event.event_start_time.strftime('%l%P') %></p>
        </div>
    </div>
<% end %>

app/views/events/new.html.erb
<div class="updateform">
	<h1>New event</h1>
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="five_sixth">
  <div class="page-header">
      <%= link_to 'Edit', edit_organization_event_path(@organization), class: "btn btn-warning right" %>
    <h1><%= @event.name %></h1>
  </div>

  <div class="row event-row text-center">
    <%= image_tag 'bruno.jpg' %>
    <div class="one_third">
      <h3>Who</h3>
      <%= @event.organization.name %>
    </div>
    <div class="one_third">
      <h3>Where</h3>
      <%= @event.location %>
    </div>
    <div class="one_third">
      <h3>When</h3>
      <%= @event.event_start_date.strftime('%A') %> at <%= @event.event_start_time.strftime('%l%P') %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="row footer text-center">
	<%= image_tag 'logo.png' %>
	<p>
		Powered by Campusvine.<br>
		Built by Heuretix.
	</p>
	<a href="http://twitter.com/campusvine" target="_blank"><%= image_tag 'twitter.png' %></a>
	<a href="http://facebook.com/campusvine" target="_blank"><%= image_tag 'facebook.png' %></a>
	<a href="#" id="monkeyfoot"><%= image_tag 'cv-footer-logo.png' %></a>
	<a href="#" target="_blank"><%= image_tag 'youtube.png' %></a>
	<a href="http://plus.google.com/110384859709338115691" target="_blank"><%= image_tag 'gplus.png' %></a>
</div>

app/views/layouts/_nav.html.erb
<div class="navigation">
	<a href="/">
		<%= image_tag 'stan.png' %>
		<h1>campusvine</h1>
	</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Events</title>
  			<%= stylesheet_link_tag    "application", :media => "all" %>
  			<%= javascript_include_tag "application" %>
  			<%= csrf_meta_tags %>
  			<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/nav' %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<div class="updateform">
	<h1>Editing organization</h1>
	<%= render 'form' %>
</div>

app/views/organizations/index.html.erb
<% @organizations.each do |organization| %>
  <div class="row org-row">
    <div class="two_thirds">
      <h3><%= organization.name %></h3>
      <p><%= organization.description %></p>
      <%= organization.website %>
    </div>
    <div class="one_third">
      <h3>Actions</h3>
      <%= link_to 'Show', organization %><br>
      <%= link_to 'Edit', edit_organization_path(organization) %><br>
      <%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<br />

<%= link_to 'New Organization', new_organization_path, class: "btn" %>

app/views/organizations/new.html.erb
<div class="updateform">
	<h1>New organization</h1>
	<%= render 'form' %>
</div>

app/views/organizations/show.html.erb
<div class="five_sixth ">
	<div class="page-header">
		<span class="right">
			<%= link_to 'New Event', new_organization_event_path(@organization), class: "btn btn-inverse" %>
			<%= link_to 'Edit', edit_organization_path(@organization), class: "btn btn-warning" %>
			<%= link_to 'Website', @organization.website, class: "btn" %>
		</span>
		<h1><%= @organization.name %></h1>
		<small><%= @organization.description %></small>
	</div>
	<br>

	 <% @organization.events.each do |event| %>
	 	<div class="row event-row text-center">
	 		<%= image_tag 'bruno.jpg' %>
	 		<div class="one_third">
	 			<h3>What</h3>
	 			<%= event.name %>
	 		</div>
	 		<div class="one_third">
	 			<h3>Where</h3>
	 			<%= event.location %>
	 		</div>
	 		<div class="one_third">
	 			<h3>When</h3>
	 			<%= event.event_start_date.strftime('%A') %> at <%= event.event_start_time.strftime('%l%P') %>
	 		</div>
	 	</div>
	 <% end %>
</div>